```sql
/*
================================================================================
TITLE: Sales Data Warehouse - Magnitude Analysis
AUTHOR: [Your Name]
DATE: [Current Date]
PURPOSE: Analyze sales distribution and performance across key dimensions

DESCRIPTION:
This script performs magnitude analysis to understand distribution patterns
and performance metrics across customers, products, and geographies.
It identifies top-performing segments and provides insights into revenue
distribution, customer demographics, and product category performance.

KEY ANALYSIS AREAS:
1. GEOGRAPHIC DISTRIBUTION - Customer counts by country
2. DEMOGRAPHIC ANALYSIS - Customer distribution by gender
3. PRODUCT PORTFOLIO - Product counts and costs by category
4. REVENUE ANALYSIS - Sales performance by product category
5. CUSTOMER VALUE - Revenue contribution by individual customers
6. GEOGRAPHIC SALES - Item distribution across countries

BUSINESS INSIGHTS PROVIDED:
- Which countries have the largest customer base?
- What is the gender distribution of customers?
- Which product categories generate the most revenue?
- Who are the top-spending customers?
- How are sales distributed geographically?

DEPENDENCIES:
- gold.fact_sales (sales transaction data)
- gold.dim_customers (customer information)
- gold.dim_product (product information)

OUTPUT: Multiple result sets showing distribution patterns and performance rankings
================================================================================
*/

--- Magnitude Analysis 


--- Find the total customers by country
select 
count(customer_id) as total_customer,
Country
from gold.dim_customers
group by Country
order by total_customer DESC


--- Find total customers by Gender
select 
count(customer_id) as total_customer,
gendr
from gold.dim_customers
group by gendr
order by total_customer DESC


--- Find total product by category
select 
count(product_id) total_product,
catagory
from gold.dim_product
group by category
order by total_product


--- What is the average cost within the category

select 
avg(cost) as average,
catagory
from gold.dim_product
group by category
order by average


--- What is the total revenue generated by each categor
select 
dp. category,
sum(fs.seals) as total_revnue
from gold.fact_sales fs 
left join gold.dim_product dp
on dp.product_key=fs.product_key
group by dp. category
order by total_revenue desc


--- Find total revenue generated by each customer
select 
dc.customer_key,
dc.first_name,
dc.last_name,
sum(fs.seals) as total_revnue
from gold.fact_sales fs
left join gold.dim_customers dc
on dc.customer_key= fs.customer_key
group by dc.customer_key,
		 dc.first_name,
		 dc.last_name
order by total_revnue desc

--- Total distribution of sold items by country 
select 
dc.Country,
sum(fs.quantity) as total_sold_items

from gold.fact_sales fs
left join gold.dim_customers dc
on dc.customer_key= fs.customer_key

group by dc.Country
order by total_sold_items desc
```
